### PR TITLE
Fix some code smells reported by Landscape

### PR DESCRIPTION
**Pull request by bittner**
* Fix some code smells (redefine built-in, unused import) [reported by Landscape](https://landscape.io/github/jcassee/django-analytical/14/messages/smell).
* Address `flake8` complaints in touched modules (except for some specific overly long lines).

Looking forward to seeing code health go up bit!

### CODE REVIEW

**Comment by bittner** [comment]
Travis-CI builds with Python 3.2 fail now, because the latest major version of `pip` has [dropped support for Python 3.2](https://pip.pypa.io/en/stable/news/#release-notes). We need to stick to `pip==7.1.2` explicitely if we want to support `Django<1.9` (1.7 and 1.8 still support Python 3.2).

**Comment by bittner** [comment]
`tox` on Travis-CI still uses `pip==8.0.2` from the site-packages, which make builds with Python 3.2 fail. I've [opened an issue at Travis-CI support](https://github.com/travis-ci/travis-ci/issues/5517) to get feedback from them on the problem.

**Comment by jcassee** [comment]
Unfortunately, this PR needs to be rebased.

**Comment by bittner** [comment]
This PR is ready for merging, @jcassee. Thanks!

**Pull request merged**
