### PR TITLE
Also test with Django 1.8 (Travis-CI)

### PR DESCRIPTION
**Pull request by bittner**
Plus white-space changes to match typically used YAML syntax (indentation of lists).

This commit may close issue #54 if all goes well.

### CODE REVIEW

**Comment by jcassee** [comment]
Cool! Could you also update `tox.ini`? It's a bit of a nuisance having to keep them in sync, but I use it locally for testing.

**Comment by bittner** [comment]
I've refactored `tox.ini` and `.travis.yml` based on the following information:

- [Generating environments, conditional settings](http://tox.readthedocs.org/en/latest/config.html#generating-environments-conditional-settings), Tox 1.9 documentation
- [Using Tox with Travis CI to Test Django Apps](http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/) by Jeremy Satterfield

I didn't find information about Travis-CI being able to handle Bash-like variable expansion (conditional settings), so the list of test environments in `.travis.yml` needs to be generated using:
``` bash
$ tox -l | xargs -I ITEM echo "  - TOXENV="ITEM
```

**Comment by jcassee** [comment]
Looks great! I don't know whether Travis supports expansion, but this is already pretty nice. Thanks!

**Comment by jcassee** [comment]
Ah, we forgot to update the changelog. I'll update it in a direct commit to master, alright?

**Pull request merged**
