### PR TITLE
Fix flake8 complaints (whitespace), add another badge

### PR DESCRIPTION
**Pull request by bittner**
This is just a start on addressing flake8 complaints. Also adds a badge in the README towards the Landscape.io service checking the code health (Pylint, flake8). This way we can monitor how code quality improves or degrades.

@jcassee You need to open an account at https://landscape.io/ (which is currently down, unfortunately) using your GitHub account name. Then the badge will start working.

### CODE REVIEW

**Comment by bittner** [comment]
Wow, isn't the Landscape report beautiful?  :heart_eyes:

**Comment by jcassee** [comment]
:smile:

**Comment by jcassee** [comment]
BTW, I had been looking for something like this for Python, thanks for finding this.

**Comment by bittner** [comment]
JFYI, [Code Climate](https://codeclimate.com/) is an alternative to Landscape, which will include [coverage for Python](http://docs.codeclimate.com/article/219-setting-up-test-coverage) in future beside their [checks](https://codeclimate.com/checks).

**Comment by jcassee** [comment]
I did not know Code Climate was preparing Python support, nice to know!

**Pull request merged**
