### PR TITLE
Add support for the Rating@Mail.ru service

### PR DESCRIPTION
**Pull request by sikmir**
Issue #87

### CODE REVIEW

**Comment by bittner** [comment]
@sikmir Do the tests pass locally on your machine? Looks like you have a spelling mistake in the source code:
``` python
ImportError: cannot import name 'RaitingMailruNode'
```
I've noticed you're using `Rating...` and `Raiting...` interchangeably in source code and documentation. Can you check which spelling is appropriate and push a fix to this PR?

**Comment by sikmir** [comment]
@bittner Yes, that's a typo. Fixed.

**Comment by bittner** [comment]
Travis is [still complaining](https://travis-ci.org/jcassee/django-analytical/jobs/125443826#L209) about the `'counter_id': self.counter_id,` line in 3 files. Is this some encoding problem?  Not sure myself.

Maybe removing the line and retyping it (= no copy+paste from outside the editor) fixes that. Can you check?

**Comment by jcassee** [comment]
@sikmir Could you rebase against the new master branch? This should trigger a rebuild that should fix the failing checks.

**Comment by bittner** [comment]
@jcassee ... apart from the decreased coverage.

@sikmir Maybe you could add a test that triggers the [TemplateSyntaxError](https://coveralls.io/jobs/14567806/source_files/496095819#L53)?

**Comment by jcassee** [comment]
`TemplateSyntaxError` was never tested. Coverage is reduced because the change adds a string. I don't think this is a problem?

**Comment by bittner** [comment]
I think we can merge this PR. What do you think, @jcassee?

**Comment by jcassee** [comment]
I had hoped @sikmir would rebase, but maybe we can just merge and fix on master.

**Comment by sikmir** [comment]
@jcassee I've rebased already.

**Comment by jcassee** [comment]
@sikmir Sorry, you are right! I mixed up the Coveralls and Travis checks.

**Comment by bittner** [comment]
@sikmir Can you merge in the changes from the master branch and resolve the conflicts? That would be very helpful.

**Comment by jcassee** [comment]
Thanks for this change and #84, Nikolay!

**Comment by jcassee** [comment]
Your changes have been released in 2.1.0 on PyPI.

**Pull request merged**
